"""
Schemas for Causal Discovery (DAG Generation).

Defines the request/response models for:
  - LLM-powered causal graph discovery (PyWhy-LLM strategy)
  - DAG Library CRUD (create, read, update, delete)
  - Human-in-the-Loop verification
"""
from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


# ── Shared Components

class CausalEdge(BaseModel):
    """
    A single directed edge in the causal graph.
    Tracks confidence, the causal reasoning, and whether it was
    generated by the LLM or manually specified by the domain expert.
    """
    source: str
    target: str
    confidence: float = 1.0
    relationship_type: str = "direct"  # "direct", "confounder", "mediator"
    reasoning: str = ""  # LLM's causal reasoning for why this edge exists
    origin: str = "manual"  # "llm" or "manual"


class VariableRoles(BaseModel):
    """
    Variable roles relative to the treatment-outcome relationship.

    These map directly to the concepts in causal inference:
    - Confounders: common causes of both treatment AND outcome
    - Mediators: variables on the causal PATH from treatment to outcome
    - Colliders: variables caused by BOTH treatment and outcome
    - Instrumental: variables that affect treatment but NOT outcome directly
    """
    confounders: list[str] = []
    mediators: list[str] = []
    colliders: list[str] = []
    instrumental_variables: list[str] = []


# ── LLM Discovery Request/Response 

class DAGDiscoveryRequest(BaseModel):
    """
    Request body for POST /causal-discovery/discover.
    
    Can be used in two modes:
      1. Session mode: provide session_id to auto-extract variables
      2. Studio mode: provide variables directly (no session needed)
    """
    session_id: Optional[str] = None
    variables: Optional[list[str]] = None  # Direct variable input for Studio mode
    treatment_col: Optional[str] = None
    outcome_col: Optional[str] = None


class DAGDiscoveryResponse(BaseModel):
    """Complete response from the causal discovery pipeline."""
    session_id: str = ""
    treatment: str
    outcome: str

    # LLM-suggested domain expertises (e.g., "marketing analytics")
    domain_expertises: list[str] = []

    # The discovered causal graph
    edges: list[CausalEdge] = []
    adjacency_list: dict[str, list[str]] = {}

    # Variable role classification
    variable_roles: VariableRoles = VariableRoles()

    # All variables that were analyzed
    variables_analyzed: list[str] = []

    # Metadata
    model_used: str = ""
    num_llm_calls: int = 0


# ── DAG Library Schemas 

class DAGCreateRequest(BaseModel):
    """
    Request body for POST /causal-discovery/dags (manual creation).
    
    Used when the user builds a DAG from scratch in the Studio
    by assigning variable roles and drawing edges manually.
    """
    name: str = Field(..., min_length=1, max_length=100)
    description: str = ""
    treatment: str = "IMC_Exposure"
    outcome: str
    edges: list[CausalEdge] = []
    variable_roles: VariableRoles = VariableRoles()


class DAGVerifyAndSaveRequest(BaseModel):
    """
    Request body for POST /causal-discovery/dags/verify-and-save.
    
    Used after the user reviews an LLM-generated DAG in the
    verification UI. Contains the (potentially modified) edges
    and roles that the user has approved.
    """
    name: str = Field(..., min_length=1, max_length=100)
    description: str = ""
    treatment: str = "IMC_Exposure"
    outcome: str
    edges: list[CausalEdge] = []
    variable_roles: VariableRoles = VariableRoles()
    domain_expertises: list[str] = []
    model_used: str = ""
    # Optional: attach to a session immediately
    session_id: Optional[str] = None


class DAGUpdateRequest(BaseModel):
    """Request body for PUT /causal-discovery/dags/{dag_id}."""
    name: Optional[str] = None
    description: Optional[str] = None
    edges: Optional[list[CausalEdge]] = None
    variable_roles: Optional[VariableRoles] = None


class SavedDAG(BaseModel):
    """
    Complete DAG document as stored in MongoDB.
    This is the response model for all DAG library endpoints.
    """
    dag_id: str
    name: str
    description: str = ""
    treatment: str
    outcome: str
    variables: list[str] = []
    edges: list[CausalEdge] = []
    adjacency_list: dict[str, list[str]] = {}
    variable_roles: VariableRoles = VariableRoles()
    creation_mode: str = "manual"  # "llm_assisted" or "manual"
    model_used: str = ""
    domain_expertises: list[str] = []
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None


class DAGListItem(BaseModel):
    """Lightweight DAG summary for list views."""
    dag_id: str
    name: str
    treatment: str
    outcome: str
    edge_count: int = 0
    variable_count: int = 0
    creation_mode: str = "manual"
    created_at: Optional[datetime] = None
